# Generated by Django 5.2.17 on 2026-09-22 20:02

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('xlsx', 'Excel workbook'), ('pdf', 'Payslip PDF')], max_length=8, verbose_name='kind')),
                ('file', models.FileField(upload_to='reports/%Y/%m/', verbose_name='file')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='generated at')),
                ('emailed_to', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None, verbose_name='emailed to')),
                ('emailed_at', models.DateTimeField(blank=True, null=True, verbose_name='emailed at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company', verbose_name='company')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='payroll.period')),
            ],
            options={
                'verbose_name': 'report file',
                'verbose_name_plural': 'report files',
                'ordering': ['-generated_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
