# Generated by Django 5.2.17 on 2026-09-22 20:02

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('unexcused_absence', 'Unexcused absence'), ('sick', 'Sick'), ('paid_leave', 'Paid leave'), ('weekly_off', 'Weekly off'), ('excused_absence', 'Excused absence')], default='present', max_length=20, verbose_name='status')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='overtime hours')),
                ('late_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='late hours')),
                ('admin_penalty_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='administrative penalty (days)')),
                ('fingerprint_penalty_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='fingerprint penalty (days)')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company', verbose_name='company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='employees.employee')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_records_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'daily record',
                'verbose_name_plural': 'daily records',
                'ordering': ['-date', 'employee__code'],
                'indexes': [models.Index(fields=['company', 'date'], name='attendance__company_fdf935_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='dailyrecord_unique_per_employee_day')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
