# Generated by Django 5.2.17 on 2026-09-22 20:02

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='total')),
                ('monthly_installment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='monthly instalment')),
                ('start_year', models.PositiveSmallIntegerField(verbose_name='start year')),
                ('start_month', models.PositiveSmallIntegerField(verbose_name='start month')),
                ('remaining', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='remaining')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company', verbose_name='company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='employees.employee')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'ordering': ['employee__code'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('month', models.PositiveSmallIntegerField(verbose_name='month')),
                ('status', models.CharField(choices=[('open', 'Open'), ('calculated', 'Calculated'), ('closed', 'Closed')], default='open', max_length=12, verbose_name='status')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='calculated at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'payroll period',
                'verbose_name_plural': 'payroll periods',
                'ordering': ['-year', '-month'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=32, verbose_name='code')),
                ('employee_name', models.CharField(max_length=200, verbose_name='name')),
                ('branch_snapshot', models.CharField(max_length=200, verbose_name='branch')),
                ('job_title_snapshot', models.CharField(blank=True, max_length=120, verbose_name='job title')),
                ('daily_hours', models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5, verbose_name='daily hours')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='base salary')),
                ('work_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='work days')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='overtime hours')),
                ('leave_allowance_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='leave allowance days')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='bonus')),
                ('other_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='other earnings')),
                ('late_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='late hours')),
                ('advances', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='advances')),
                ('carried_advance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='carried advance')),
                ('admin_penalty_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='administrative penalty days')),
                ('fingerprint_penalty_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='fingerprint penalty days')),
                ('unexcused_absence_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='unexcused absence days')),
                ('sick_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='sick days')),
                ('insurable_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='insurable salary')),
                ('deviations', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='deviations')),
                ('shortage_custody', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='shortage / custody')),
                ('work_days_value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='work days value')),
                ('overtime_value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='overtime value')),
                ('leave_allowance_value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='leave allowance value')),
                ('total_earnings', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='total earnings')),
                ('late_value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='late value')),
                ('admin_penalty_value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='administrative penalty value')),
                ('fingerprint_penalty_value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='fingerprint penalty value')),
                ('unexcused_absence_value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='unexcused absence value')),
                ('sick_value', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='sick value')),
                ('insurance_and_tax', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='insurance and tax')),
                ('total_deductions', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='total deductions')),
                ('net_salary', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20, verbose_name='net salary')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('overrides', models.JSONField(blank=True, default=dict, verbose_name='overrides')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='warnings')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company', verbose_name='company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.period')),
            ],
            options={
                'verbose_name': 'payroll line',
                'verbose_name_plural': 'payroll lines',
                'ordering': ['employee_code'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('bonus', 'Bonus'), ('other_earning', 'Other earning'), ('advance', 'Advance'), ('carried_advance', 'Carried advance'), ('deviation', 'Deviation'), ('shortage_custody', 'Shortage / custody'), ('leave_allowance_days', 'Leave allowance (days)')], max_length=24, verbose_name='kind')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='amount')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.period')),
            ],
            options={
                'verbose_name': 'monthly adjustment',
                'verbose_name_plural': 'monthly adjustments',
                'ordering': ['employee__code', 'kind'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month'), name='period_unique_per_company_month'),
        ),
        migrations.AddIndex(
            model_name='payrollline',
            index=models.Index(fields=['company', 'period'], name='payroll_pay_company_82cca8_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('period', 'employee'), name='payrollline_unique_per_period_employee'),
        ),
        migrations.AddIndex(
            model_name='monthlyadjustment',
            index=models.Index(fields=['company', 'period', 'employee'], name='payroll_mon_company_07a8a1_idx'),
        ),
    ]
