# Generated by Django 5.2.17 on 2026-09-22 20:02

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('report_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None, verbose_name='report recipients')),
                ('report_day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='report day of month')),
                ('report_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2, verbose_name='report language')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='code')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['name_ar'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name_ar'), name='branch_unique_name_per_company')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('month_day_basis', models.PositiveSmallIntegerField(default=30, verbose_name='month day basis')),
                ('overtime_multiplier', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=6, verbose_name='overtime multiplier')),
                ('absence_multiplier', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=6, verbose_name='unexcused absence multiplier')),
                ('sick_deduction_rate', models.DecimalField(decimal_places=4, default=Decimal('0.25'), max_digits=6, verbose_name='sick deduction rate')),
                ('insurance_employee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.11'), max_digits=6, verbose_name='insurance rate')),
                ('fingerprint_penalty_base', models.CharField(choices=[('earned', 'Earned days value (H)'), ('base', 'Base salary (F)')], default='earned', max_length=8, verbose_name='fingerprint penalty base')),
                ('default_daily_hours', models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5, verbose_name='default daily hours')),
                ('income_tax_enabled', models.BooleanField(default=False, verbose_name='income tax enabled')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'payroll policy',
                'verbose_name_plural': 'payroll policies',
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('company', 'effective_from'), name='policy_unique_version_per_company')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
