# Generated by Django 5.2.17 on 2026-09-22 20:10

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="branch",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="payrollpolicy",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
