# Generated by Django 5.2.17 on 2026-09-22 20:02

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('name_ar', models.CharField(max_length=200, verbose_name='name (Arabic)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='name (English)')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='job title')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='national ID')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='hire date')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='termination date')),
                ('daily_hours', models.DecimalField(decimal_places=2, default=Decimal('9'), max_digits=5, verbose_name='daily hours')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='base salary')),
                ('insurable_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='insurable salary')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['code'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='base salary')),
                ('insurable_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='insurable salary')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='companies.company', verbose_name='company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='employees.employee')),
            ],
            options={
                'verbose_name': 'salary history',
                'verbose_name_plural': 'salary history',
                'ordering': ['-effective_from'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'is_active'], name='employees_e_company_44de86_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='employee_unique_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='salaryhistory',
            constraint=models.UniqueConstraint(fields=('employee', 'effective_from'), name='salary_unique_per_employee_date'),
        ),
    ]
