# Generated by Django 5.2.17 on 2026-09-22 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('close', 'Close period'), ('reopen', 'Reopen period'), ('calculate', 'Calculate period'), ('override', 'Override payroll line')], max_length=16, verbose_name='action')),
                ('model', models.CharField(max_length=64, verbose_name='model')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='object id')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='before')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='after')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='audit_audit_company_832522_idx'), models.Index(fields=['model', 'object_id'], name='audit_audit_model_6c2be1_idx')],
            },
        ),
    ]
